#.(progn
    (in-package #:cl-user)
    nil)

(defpackage #:observability-kit/otlp
  (:nicknames #:cl-observability-kit/otlp)
  (:use #:cl)
  (:import-from #:observability-kit
                #:observability-error
                #:metric
                #:metric-p
                #:metric-registry
                #:metric-registry-p
                #:meter-provider
                #:meter-provider-p
                #:metric-snapshot
                #:metric-snapshot-p
                #:metric-snapshot-name
                #:metric-snapshot-help
                #:metric-snapshot-type
                #:metric-snapshot-unit
                #:metric-snapshot-samples
                #:metric-snapshot-resource
                #:metric-sample-labels
                #:metric-sample-value
                #:metric-sample-count
                #:metric-sample-sum
                #:metric-sample-buckets
                #:metric-sample-p
                #:resource-attributes
                #:span-record
                #:span-record-p
                #:span-record-trace-id
                #:span-record-span-id
                #:span-record-parent-span-id
                #:span-record-name
                #:span-record-kind
                #:span-record-start-time
                #:span-record-end-time
                #:span-record-duration
                #:span-record-status
                #:span-record-status-message
                #:span-record-trace-flags
                #:span-record-sampled-p
                #:span-record-recording-p
                #:span-record-attributes
                #:span-record-events
                #:span-record-links
                #:span-record-resource
                #:span-record-tracer-name
                #:span-record-tracer-version
                #:span-record-tracer-schema-url
                #:span-event-name
                #:span-event-timestamp
                #:span-event-attributes
                #:span-link-context
                #:span-link-attributes
                #:instrumentation-context-trace-id
                #:instrumentation-context-span-id
                #:instrumentation-context-trace-flags
                #:instrumentation-context-remote-p
                #:log-record
                #:log-record-p
                #:log-record-timestamp
                #:log-record-severity-text
                #:log-record-severity-number
                #:log-record-body
                #:log-record-attributes
                #:log-record-context
                #:log-record-resource
                #:log-record-scope-name
                #:log-record-scope-version
                #:log-record-scope-schema-url
                #:proper-list-p
                #:+infinity+)
  (:export #:metric-snapshot->otlp
           #:snapshot->otlp
           #:registry->otlp
           #:span-record->otlp
           #:traces->otlp
           #:log-record->otlp
           #:logs->otlp))
