#.(progn
    (in-package #:cl-user)
    nil)

(defpackage #:observability-kit
  (:nicknames #:cl-observability-kit)
  (:use #:cl)
  (:export
   ;; Conditions
   #:observability-error
   #:validation-error
   #:invalid-metric-name
   #:invalid-label-name
   #:invalid-label-value
   #:invalid-label-set
   #:unsafe-attribute-name
   #:metric-definition-conflict
   #:metric-cardinality-exceeded
   #:metric-operation-error
   #:health-error
   #:health-check-timeout
   #:health-check-cancelled
   #:tracing-error
   #:invalid-span-name
   #:tracer-provider-shutdown
   #:span-operation-error
   #:logging-error
   #:invalid-log-severity
   #:log-provider-shutdown
   #:configuration-error
   #:configuration-error-name
   #:propagation-error
   #:invalid-traceparent
   #:http-error
   #:invalid-http-method
   #:invalid-http-method-method
   #:invalid-http-status
   #:invalid-http-status-status

   ;; Metrics and snapshots
   #:metric-registry
   #:metric-registry-p
   #:make-metric-registry
   #:metric
   #:metric-p
   #:counter-p
   #:up-down-counter-p
   #:observable-counter-p
   #:observable-gauge-p
   #:observable-up-down-counter-p
   #:gauge-p
   #:histogram-p
   #:metric-name
   #:metric-help
   #:metric-unit
   #:metric-label-names
   #:metric-kind
   #:metric-registry-metrics
   #:metric-registry-scope-name
   #:metric-registry-scope-version
   #:metric-registry-scope-schema-url
   #:define-counter
   #:define-up-down-counter
   #:define-observable-counter
   #:define-observable-gauge
   #:define-observable-up-down-counter
   #:define-gauge
   #:define-histogram
   #:metric-inc
   #:metric-set
   #:metric-observe
   #:metric-snapshot
   #:metric-snapshot-p
   #:metric-snapshot-name
   #:metric-snapshot-help
   #:metric-snapshot-type
   #:metric-snapshot-unit
   #:metric-snapshot-label-names
   #:metric-snapshot-samples
   #:metric-snapshot-resource
   #:metric-snapshot-scope-name
   #:metric-snapshot-scope-version
   #:metric-snapshot-scope-schema-url
   #:metric-snapshot-temporality
   #:metric-snapshot-timestamp
   #:metric-snapshot-start-time
   #:metric-sample
   #:metric-sample-p
   #:metric-sample-labels
   #:metric-sample-value
   #:metric-sample-count
   #:metric-sample-sum
   #:metric-sample-buckets
   #:metric-sample-timestamp
   #:metric-sample-start-time
   #:+infinity+

   ;; Metric providers and readers
   #:meter-provider
   #:meter-provider-p
   #:make-meter-provider
   #:meter-provider-resource
   #:meter-provider-meters
   #:meter-provider-readers
   #:meter-provider-shutdown-p
   #:meter-provider-last-error
   #:force-flush-meter-provider
   #:shutdown-meter-provider
   #:meter
   #:meter-p
   #:make-meter
   #:meter-name
   #:meter-version
   #:meter-schema-url
   #:meter-provider
   #:meter-registry
   #:metric-reader
   #:metric-reader-p
   #:make-metric-reader
   #:metric-reader-source
   #:metric-reader-shutdown-p
   #:metric-reader-last-error
   #:metric-reader-last-snapshots
   #:register-metric-reader
   #:collect-metric-reader
   #:force-flush-metric-reader
   #:metric-reader-force-flush
   #:shutdown-metric-reader
   #:metric-reader-shutdown
   #:periodic-metric-reader
   #:periodic-metric-reader-p
   #:make-periodic-metric-reader
   #:periodic-metric-reader-reader
   #:periodic-metric-reader-interval
   #:periodic-metric-reader-running-p
   #:periodic-metric-reader-shutdown-p
   #:periodic-metric-reader-last-error
   #:start-periodic-metric-reader
   #:collect-periodic-metric-reader
   #:force-flush-periodic-metric-reader
   #:shutdown-periodic-metric-reader

   ;; Health checks
   #:health-registry
   #:health-registry-p
   #:make-health-registry
   #:health-registry-clock
   #:health-registry-monotonic-units-per-second
   #:health-check
   #:health-check-p
   #:health-check-name
   #:health-check-kind
   #:health-check-function
   #:health-check-timeout
   #:health-check-cancellation-grace-period
   #:register-health-check
   #:unregister-health-check
   #:health-registry-checks
   #:health-registry-last-results
   #:run-health-checks
   #:health-result
   #:health-result-p
   #:health-result-name
   #:health-result-kind
   #:health-result-status
   #:health-result-value
   #:health-result-condition
   #:health-result-duration
   #:health-status
   #:define-health-check
   #:make-cancellation-token
   #:cancellation-token-p
   #:cancel-cancellation-token
   #:cancellation-requested-p
   #:cancellation-reason

   ;; Shared validation protocol
   #:proper-list-p

   ;; Instrumentation context
   #:instrumentation-context
   #:instrumentation-context-p
   #:make-instrumentation-context
   #:instrumentation-context-trace-id
   #:instrumentation-context-span-id
   #:instrumentation-context-trace-flags
   #:instrumentation-context-attributes
   #:instrumentation-context-baggage
   #:instrumentation-context-tracestate
   #:instrumentation-context-remote-p
   #:context-attribute
   #:context-with-attribute
   #:context-with-attributes
   #:current-instrumentation-context
   #:with-instrumentation-context
   #:capture-instrumentation-context
   #:call-with-captured-instrumentation-context
   #:with-captured-instrumentation-context

   ;; Resources
   #:resource
   #:resource-p
   #:make-resource
   #:resource-attributes
   #:resource-attribute
   #:resource-with-attribute
   #:resource-with-attributes

   ;; SDK configuration
   #:sdk-configuration
   #:sdk-configuration-p
   #:read-sdk-configuration
   #:sdk-configuration-disabled-p
   #:sdk-configuration-service-name
   #:sdk-configuration-resource-attributes
   #:sdk-configuration-resource
   #:sdk-configuration-propagator
   #:sdk-configuration-metric-export-interval
   #:sdk-configuration-metric-export-timeout
   #:sdk-configuration-trace-sampler
   #:sdk-configuration-log-level

   ;; Tracing
   #:tracer-provider
   #:tracer-provider-p
   #:make-tracer-provider
   #:make-trace-id-ratio-sampler
   #:make-parent-based-sampler
   #:tracer-provider-resource
   #:tracer-provider-clock
   #:tracer-provider-tracers
   #:tracer-provider-span-processors
   #:tracer-provider-shutdown-p
   #:tracer-provider-last-export-error
   #:force-flush-tracer-provider
   #:shutdown-tracer-provider
   #:span-processor
   #:span-processor-p
   #:make-span-processor
   #:span-processor-on-start
   #:span-processor-on-end
   #:span-processor-force-flush
   #:span-processor-shutdown
   #:span-processor-error-handler
   #:register-span-processor
   #:tracer
   #:tracer-p
   #:make-tracer
   #:tracer-name
   #:tracer-version
   #:tracer-schema-url
   #:span
   #:span-p
   #:start-span
   #:end-span
   #:span-name
   #:span-update-name
   #:span-kind
   #:span-trace-id
   #:span-id
   #:span-parent-span-id
   #:span-trace-flags
   #:span-start-time
   #:span-end-time
   #:span-duration
   #:span-status
   #:span-status-message
   #:span-recording-p
   #:span-sampled-p
   #:span-ended-p
   #:span-attributes
   #:span-set-attribute
   #:span-event
   #:span-event-p
   #:span-event-name
   #:span-event-timestamp
   #:span-event-attributes
   #:span-events
   #:span-add-event
   #:span-link
   #:span-link-p
   #:span-link-context
   #:span-link-attributes
   #:span-links
   #:span-add-link
   #:span-set-status
   #:span-record-exception
   #:span-context
   #:span-record
   #:span-record-p
   #:span-record-trace-id
   #:span-record-span-id
   #:span-record-parent-span-id
   #:span-record-name
   #:span-record-kind
   #:span-record-start-time
   #:span-record-end-time
   #:span-record-duration
   #:span-record-status
   #:span-record-status-message
   #:span-record-trace-flags
   #:span-record-sampled-p
   #:span-record-recording-p
   #:span-record-attributes
   #:span-record-events
   #:span-record-links
   #:span-record-resource
   #:span-record-tracer-name
   #:span-record-tracer-version
   #:span-record-tracer-schema-url
   #:current-span
   #:with-span
   #:call-with-span
   #:*current-span*

   ;; Structured logs
   #:log-record
   #:log-record-p
   #:make-log-record
   #:log-record-timestamp
   #:log-record-severity
   #:log-record-severity-text
   #:log-record-severity-number
   #:log-record-body
   #:log-record-attributes
   #:log-record-context
   #:log-record-resource
   #:log-record-scope-name
   #:log-record-scope-version
   #:log-record-scope-schema-url
   #:log-processor
   #:log-processor-p
   #:make-log-processor
   #:log-processor-on-emit
   #:log-processor-force-flush
   #:log-processor-shutdown
   #:log-processor-error-handler
   #:log-provider
   #:log-provider-p
   #:make-log-provider
   #:log-provider-resource
   #:log-provider-loggers
   #:log-provider-processors
   #:log-provider-shutdown-p
   #:log-provider-last-error
   #:force-flush-log-provider
   #:shutdown-log-provider
   #:register-log-processor
   #:logger
   #:logger-p
   #:make-logger
   #:logger-provider
   #:logger-name
   #:logger-version
   #:logger-schema-url
   #:emit-log
   #:emit-log-record

   ;; W3C propagation
   #:format-traceparent
   #:parse-traceparent
   #:format-baggage
   #:parse-baggage
   #:inject-trace-context
   #:extract-trace-context
   #:propagator
   #:propagator-p
   #:make-propagator
   #:propagator-inject
   #:propagator-extract
   #:make-w3c-propagator
   #:make-composite-propagator
   #:make-b3-propagator
   #:make-b3-multi-propagator
   #:make-jaeger-propagator
   #:make-xray-propagator

   ;; HTTP semantic conventions
   #:http-request-attributes
   #:http-response-attributes
   #:span-set-http-request
   #:span-set-http-response))
